version: '3.8'
services:
  server:
    build: 
      context: ./server
    ports:
      - "3001:3001"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
    volumes:
      - pg-data:/var/lib/postgresql/data
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./client:/usr/app # Montez le dossier client dans le conteneur
      - /usr/app/node_modules # Assurez-vous de ne pas écraser node_modules
    environment:
      - NODE_ENV=development

volumes:
  pg-data: {}